// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApbKDBrL-4TL4U_NIEjc6YBEYdEHVpGZw',
    appId: '1:19132566447:web:4e02033e61b6384eecfd5a',
    messagingSenderId: '19132566447',
    projectId: 'campusconnect-3a34e',
    authDomain: 'campusconnect-3a34e.firebaseapp.com',
    storageBucket: 'campusconnect-3a34e.firebasestorage.app',
    measurementId: 'G-6EKSVDPKYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdS34CQjs5LhWEu79D5K2vbGZmB34u7co',
    appId: '1:19132566447:android:c98e1529d2832a5fecfd5a',
    messagingSenderId: '19132566447',
    projectId: 'campusconnect-3a34e',
    storageBucket: 'campusconnect-3a34e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB41Wd--pgSu3d64Wqj-IQ08X4dfxXVwHw',
    appId: '1:19132566447:ios:7c585b96da48530decfd5a',
    messagingSenderId: '19132566447',
    projectId: 'campusconnect-3a34e',
    storageBucket: 'campusconnect-3a34e.firebasestorage.app',
    iosBundleId: 'com.ali.campusconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB41Wd--pgSu3d64Wqj-IQ08X4dfxXVwHw',
    appId: '1:19132566447:ios:7c585b96da48530decfd5a',
    messagingSenderId: '19132566447',
    projectId: 'campusconnect-3a34e',
    storageBucket: 'campusconnect-3a34e.firebasestorage.app',
    iosBundleId: 'com.ali.campusconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApbKDBrL-4TL4U_NIEjc6YBEYdEHVpGZw',
    appId: '1:19132566447:web:65a462aa8236ac86ecfd5a',
    messagingSenderId: '19132566447',
    projectId: 'campusconnect-3a34e',
    authDomain: 'campusconnect-3a34e.firebaseapp.com',
    storageBucket: 'campusconnect-3a34e.firebasestorage.app',
    measurementId: 'G-3JRJVX65TQ',
  );
}
